# Generated by Django 4.2.18 on 2025-01-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_date_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
