# Generated by Django 4.2.18 on 2025-01-26 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_date_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_added',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
